from collections import defaultdict
import pandas as pd

# Original counts from the first table
original_counts = {
    "Uncultured fungus": 8,
    "Penicillium brevicompactum": 7,
    "Malassezia nana": 5,
    "Basidiomycete symbiont": 3,
    "Uncultured Uromyces": 3,
    "Lachancea thermotolerans": 3,
    "Trichoderma virens": 2,
    "Trichoderma atroviride": 2,
    "Didymella sp.": 2,
    "Mucor moelleri": 1,
    "Fungal sp.": 1,
    "Fusarium proliferatum": 1,
    "Floccularia albolanaripes": 1,
    "Zymoseptoria crescenta": 1,
    "Aspergillus versicolor": 1,
    "Diaporthe batatas": 1,
    "Aspergillus pseudoglaucus": 1,
    "Bolbitius titubans": 1,
    "Neofusicoccum parvum": 1,
    "uncultured Pyronemataceae": 1,
    "Uncultured Hebeloma": 1,
    "[Candida] sake": 1,
    "Fonsecaea erecta": 1,
    "Holtermanniella takashimae": 1,
    "Leptosphaeria maculans": 1,
    "Mucor shermaniae": 1,
    "Cetrelia cetrarioides": 1,
    "Pseudogymnoascus verrucosus": 1,
    "Colletotrichum gloeosporioides": 1,
    "Trichosporon asahii": 1,
    "Aspergillus unguis": 1,
    "Aspergillus karnatakaensis": 1,
    "Arthroderma cuniculi": 1,
    "Xylona heveae": 1,
    "Lenzites betulinus": 1,
    "Moniliella acetoabutens": 1,
    "Moniliella spathulata": 1,
    "Nigrospora oryzae": 1,
    "Daldinia caldariorum": 1,
    "Coltricia sp.": 1,
    "Mucor sp.": 1,
    "Puccinia sp.": 1,
    "Quambalaria eucalypti": 1,
    "Naganishia globosa": 1,
    "Cordyceps militaris": 1,
    "Rhodotorula graminis": 1,
    "Fusarium venenatum": 1,
    "Inosperma sp.": 1,
    "Holtermannia saccardoi": 1,
    "Mucorales sp.": 1,
    "Penicillium digitatum": 1,
    "Phallus ravenelii": 1,
    "Saccharomyces kudriavzevii": 1,
}

# New counts to be added
new_counts = {
    "Pseudogymnoascus pannorum": 1,
    "Didymella sp.": 3,
    "Serendipita sp.": 1,
    "Uncultured zygomycete": 2,
    "Uncultured Uromyces": 1,
    "Dendrothele sp.": 2,
    "Phaeodiaporthe appendiculata": 1,
    "Penicillium brevicompactum": 18,
    "Uncultured Capnodiales": 1,
    "Trichocladium griseum": 1,
    "Henningsomyces sp.": 3,
    "Uncultured fungus": 12,
    "Penicillium sp.": 2,
    "Peziza badia": 1,
    "[Candida] duobushaemulonis": 1,
    "Aspergillus karnatakaensis": 1,
    "Tritirachium sp.": 1,
    "Nolanea sp.": 1,
    "Mucor sp.": 6,
    "Colletotrichum gloeosporioides": 1,
    "Malassezia nana": 7,
    "Rhizopus oryzae": 1,
    "Penicillium chrysogenum": 1,
    "uncultured fungus": 3,
    "Arcticomyces warmingii": 1,
    "Penicillium spinulosum": 1,
    "Ceraceosorus marieclarkiae": 1,
    "Henningsomyces bambusae": 5,
    "Uncultured Penicillium": 1,
    "Inocybe impexa": 1,
    "Zymoseptoria crescenta": 2,
    "Arrhenia bigelowii": 1,
    "Puccinia sp.": 3,
    "Puccinia modiolae": 1,
    "Mucor shermaniae": 4,
    "Lenzites betulinus": 1,
    "Mucor circinelloides": 4,
    "Ascomycota sp.": 1,
    "Ramariopsis kunzei": 1,
    "Leucosporidium sp.": 1,
    "Fusarium proliferatum": 1,
    "Aspergillus versicolor": 1,
    "Cryptococcus neoformans": 1,
    "Mucor mucedo": 1,
    "Drechmeria coniospora": 1,
    "Amanita fulva": 1,
    "Roussoella sp.": 1,
    "Uncultured Pseudogymnoascus": 1,
    "Malassezia japonica": 2,
    "Clitopilus umbilicatus": 2,
    "Uncultured Exidiaceae": 1,
    "L. scottii": 1,
    "Aspergillus sclerotioniger": 1,
    "Basidiomycete symbiont": 2,
    "Aspergillus pseudoglaucus": 1,
    "Starmerella sp.": 1,
    "Aspergillus ochraceus": 1,
    "Mucorales sp.": 1,
    "Kwoniella shivajii": 1,
    "Massaria ariae": 1,
    "Rhodotorula kratochvilovae": 1,
    "Pleospora pelagica": 1,
    "Lecanoromycetes sp.": 1,
    "Fungal sp.": 1,
    "Apophysomyces variabilis": 1,
    "Flammulina filiformis": 1,
    "Tomentella sp.": 1,
    "Leucoagaricus gongylophorus": 1
}

# Combine counts
combined_counts = defaultdict(int, original_counts)
for species, count in new_counts.items():
    combined_counts[species] += count

# Create a sorted DataFrame
df_combined = pd.DataFrame(combined_counts.items(), columns=["Fungal Species", "Count"])
df_combined = df_combined.sort_values(by="Count", ascending=False).reset_index(drop=True)
df_combined.head(10)  # Show top 10 for preview
